apiVersion: v1
kind: Service
metadata:
  name: assignment-service
  labels:
    name: assignment-app-service
    app: demo-assignment-app
spec:
  type: NodePort
  selector:
    name: assignment-app-pod
    app: demo-assignment-app
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30005
