apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-app-deploy
  labels:
    name: assignment-app-deploy
    app: demo-assignment-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: assignment-app-pod
      app: demo-assignment-app
  template:
    metadata:
      name: assignment-app-pod
      labels:
        name: assignment-app-pod
        app: demo-assignment-app
    spec:
      containers:
      - name: assignment-app
        image: vijayshiyani/assignment:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        # volumeMounts:
        #   - name: "dotenv"
        #     mountPath: "/usr/src/app/.env"
        #     subPath: "dotenv.env"    
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 10
    # volumes:
    #   - name: "dotenv"
    #     configMap:
    #       name: "dotenv"
